services:

  clamav-app:
    image: nfrastack/clamav:latest
    container_name: clamav-app
    ports:
      - 3310:3310
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver

      - DEFINITIONS_UPDATE_FREQUENCY=60
    networks:
      - services
    restart: always

networks:
  services:
    external: true

