name: Build Image

on:
  push:
    paths:
      - '**'
      - '!README.md'

jobs:
  build:
    uses: nfrastack/gha/.github/workflows/main.yml@main
    with:
      platforms: amd64,arm64
      version: ''
    secrets: inherit