name: Build and Push Docker Image

on:
  push:
    paths:
      - '**'
      - '!README.md'

jobs:
  build:
    uses: nfrastack/gha/.github/workflows/default_amd64_arm64_modern.yml@main
    with:
      build_file: Containerfile
      platforms: linux/amd64,linux/arm64
      version: ""
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
