name: "build_image"

on:
  push:
    paths:
      - "**"
      - "!README.md"

jobs:
  build:
    uses: nfrastack/gha/.github/workflows/test.yml@main
    with:
      platforms: linux/amd64
    secrets: inherit
