name: "manual_build_image"

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Target platforms (comma-separated, e.g. amd64,arm64)'
        required: false
        default: 'amd64,arm64'
      CLAMAV_VERSION:
        description: 'Override ClamAV version'
        required: false

jobs:
  prepare:
    uses: nfrastack/gha/.github/workflows/encrypt.yml@main
    secrets: inherit
  build:
    needs: prepare
    uses: nfrastack/gha/.github/workflows/build.yml@main
    with:
      platforms: ${{ github.event.inputs.platforms }}
      version: ${{ github.event.inputs.CLAMAV_VERSION }}
    secrets: inherit
  cleanup:
    needs: build
    uses: nfrastack/gha/.github/workflows/remove_artifacts.yml@main
    secrets: inherit
